### PR TITLE
Adding wikiVisual Upload log

### PR DESCRIPTION
**Pull request by ghost**
On wikiHow, all image uploads are logged. wikiVisual (also known as wikiPhotos) is wikiHow's commercial image creation service. Any **fully published** article can be nominated for professional images from wikiVisual. See [here](https://www.wikihow.com/index.php?title=Special%3ALog&type=upload&user=WikiVisual&page=&year=2017&month=-1&tagfilter=&hide_patrol_log=1) for more information.

### CODE REVIEW

**Comment by ghost** [comment]
Oh, and I forgot to mention, all the images on damn.dog right now are from wikiVisual. Their style of drawing is quite unique. An example of their style is [this](https://www.wikihow.com/images/4/43/Be-a-Hindu-Step-1.jpg).

**Comment by ghost** [comment]
@AhoyLemon - Are you all good with this?

**Comment by AhoyLemon** [comment]
Hey @ItsPugle 

Question on this: Do you know anything about how artists submit their illustrations into the wikiVisual system? I've wanted to do an interview with wikiHow illustrators, but I couldn't figure out how to reeach out to anybody because wikiVisual processed all these images.

**Comment by ghost** [comment]
Hey, @AhoyLemon,

Here's what I know of it:

- wikiHow hires an illustrator to create the images
- The illustrator has the login details for the [wikiVisual Account](https://www.wikihow.com/User:WikiVisual)
- The illustrator uploads the image to the WikiVisual account
- The wikiHow account (it's a bot) adds the images to each article based on the name of the image.

Ta Da.

If you wanted to get in touch with an illustrator, probably email anna@wikihow.com. She's the Community Manager. Otherwise, wiki@wikihow.com is the general email for enquiries. Anna though, would be the person replying to it :)

**Comment by AhoyLemon** [comment]
Great! I'll reach out to Anna, thanks.

And I'll get this commit in there when I get a chance - it's a busy weekend for me.

**Comment by ghost** [comment]
Awesome! 
Going forward, I might be doing some more non-coding PR's

**Pull request merged**
